main: com.moiyri.gardenwar.GardenWar
name: GardenWar
version: 0.0.1

commands:
  gardenwar:
    aliases: gw
    description: This is a basic command.
    usage: Welcome to <name>! version <version>.
    permission: gardenwar.setup
    permission-message: You don't have <permission>